# name
name: siamese_binary_1205

# data
data_path: data/data_10p.csv
task: binary
split: balanced_fillin
tr_perc: 0.8

# model
model: siamese
h1: 128
h2: 128
lr: 1e-4
wd: 1e-5
tr_epochs: 5000
combinatorial_func: binary