# name
name: approx_siamese_approximation

# data
data_path: data/data_10p.csv
task: approximation
split: balanced_fillin
tr_perc: 0.8

# model
model: siamese
h1: 512
h2: 256
lr: 1e-5
wd: 1e-8
tr_epochs: 30000
combinatorial_func: approximation