# name
name: approx_siamese_bin_bin

# data
data_path: data/data_10p.csv
task: binary
split: balanced_fillin
tr_perc: 0.8

# model
model: siamese
h1: 512
h2: 256
lr: 1e-3
wd: 1e-5
tr_epochs: 30000
combinatorial_func: binary