# name
name: siamese_1205

# data
data_path: data/data_10p.csv
task: multiclass
brackets: [5, 10, 20]
split: balanced_fillin
tr_perc: 0.8

# model
model: siamese
h1: 2000
h2: 100
lr: 1e-5
wd: 1e-7
tr_epochs: 10000
